services:
  postgres:
    image: postgres:16
    environment:
      - "POSTGRES_USER=safee"
      - "POSTGRES_PASSWORD=safee"
      - "POSTGRES_DB=safee"
    ports:
      - "25432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U safee"]
      interval: 2s
      timeout: 5s
      retries: 5
    volumes:
      - "../database/tests/:/tests"
      - postgres-data:/var/lib/postgresql/data
    networks:
      - safee_net

  redis:
    image: redis:7
    ports:
      - "26379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 5
    networks:
      - safee_net

volumes:
  postgres-data:

networks:
  safee_net:
    name: safee_net
