name: TypeScript CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - prod
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  custom-lint:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get more git history
        run: git fetch --depth=1 origin main
      - name: Custom lints
        run: ./custom-lints.sh

  fmt:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js 20.19.0
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20.19.0
      - name: Install node_modules
        run: npm ci
      - name: Run fmt
        run: npm run --workspaces --if-present fmt:check
  prepare:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    outputs:
      lint: ${{ steps.list.outputs.lint }}
      check: ${{ steps.list.outputs.check }}
      test: ${{ steps.list.outputs.test }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install just
        uses: extractions/setup-just@v3
        with: 
          just-version: 1.28.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: List tasks
        id: list
        run: |
          echo "lint=$(just lint all list)" >> "${GITHUB_OUTPUT}"
          echo "check=$(just check all list)" >> "${GITHUB_OUTPUT}"
          echo "test=$(just test all list)" >> "${GITHUB_OUTPUT}"

  lint-each:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        package: ${{ fromJson(needs.prepare.outputs.lint) }}
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install just
        uses: extractions/setup-just@v3
        with: 
          just-version: 1.28.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.js 20.19.0
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20.19.0
      - name: Install node_modules
        run: npm ci
      - name: Run lint
        run: just lint ${{ matrix.package }}
  lint:
    runs-on: ubuntu-latest
    needs: lint-each
    if: ${{ always() }}
    steps:
      - name: Verify all lint-each runs succeeded
        run: |
          if [ "${{ needs.lint-each.result }}" != "success" ]; then
            echo "Some lint-each runs failed."
            exit 1
          fi

  test-each:
    runs-on: ubuntu-latest
    needs: prepare
    permissions:
      contents: read
      packages: read
    strategy:
      matrix:
        package: ${{ fromJson(needs.prepare.outputs.test) }}
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install just
        uses: extractions/setup-just@v3
        with: 
          just-version: 1.28.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.js 20.19.0
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20.19.0
      - name: Install node_modules
        run: npm ci
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run: just test ${{ matrix.package }}
      - name: Docker teardown
        if: ${{ always() }}
        run: just stop-test
  test:
    runs-on: ubuntu-latest
    needs: test-each
    if: ${{ always() }}
    steps:
      - name: Verify all test-each runs succeeded
        run: |
          if [ "${{ needs.test-each.result }}" != "success" ]; then
            echo "Some test-each runs failed."
            exit 1
          fi
